sudo: true
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

language: python
python:
 - "3.6"

cache: pip

install:
  - pip install -r requirements.txt
  - curl -O http://central.maven.org/maven2/org/apache/avro/avro-tools/1.8.2/avro-tools-1.8.2.jar


script:
  python3 -m pylint src/
